apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/conmeobeou1253/app-repo.git"
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
